## ======================================
## OpenRouteService Configuration
## ======================================
#openroute.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjcwZWQwOTJlMTNiNzRiN2Y5OGM2ZjE2ZWI0NjNkMzI1IiwiaCI6Im11cm11cjY0In0=
#openroute.api.url=https://api.openrouteservice.org/v2/directions/driving-car
#
## Optional: Cache duration (in seconds)
#openroute.cache.ttl=86400


# OpenRouteService
openroute.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjcwZWQwOTJlMTNiNzRiN2Y5OGM2ZjE2ZWI0NjNkMzI1IiwiaCI6Im11cm11cjY0In0=
openroute.base.fare=30.0
openroute.rate.per.km=2.0
# ======================================
# Database Configuration
# ======================================
spring.datasource.url=jdbc:mysql://localhost:3306/ride_sharing_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sweekrithi123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ======================================
# Server Configuration
# ======================================
server.port=8080

jwt.secret=mySecretKeyForJwtTokenGeneration123456789
jwt.expiration=86400000

# ======================================o
# Email (Gmail SMTP) Configuration
# ======================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rideshareapp416@gmail.com
spring.mail.password=xyxw pbbk hmpq vrao
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ======================================
# Razorpay Payment Gateway Configuration
# ======================================kubccixaps
razorpay.key.id=rzp_test_Rmi7tKDT5yD27j
razorpay.key.secret=8UdrJCFnCIsXMpJxTQdpPAUj
razorpay.currency=INR